language: java
env:
  global:
    secure: Z9jk1hasOUPPYtvscAOwqzrAA1N3+brEl79pJwfx8I5kLDVnGBqbBhuEiG6gTLCEULjMMVQUX92mCV2Hwik1Z/zNgM6jxb7rXYlAwQ18HzeDsSE5zIvsJht1glPIo6aPrtNXKf0owBLIZOwEXFMxBacy+qrMdj0pThmR7eeh78o=
jdk:
- oraclejdk8
install:
- ./gradlew --refresh-dependencies --stacktrace
script:
- ./gradlew build artifactoryPublish
after_success:
- ./gradlew jacocoTestReport coveralls
after_failure:
- cat ./build/test-results/*.xml
