language: java
env:
  global:
    secure: go0uDddwW/NIRZ0UuToaSLAv/w1Nmg+lFJh0hhiKFxAIsukFsPSc74us0gwErvg+kngyXDxmB7N7W2ndA54toZUjNbpIogla+Gw7W08QxiaSsTqVqQ9OYSHj+EabO5trFZ863F5dEWmGRod99tbqrp20R5DPPrrV1rDkhkClVVk=

jdk:
  - oraclejdk8

install:
  - ./gradlew --refresh-dependencies --stacktrace

script:
  - ./gradlew build

after_success:
  - ./gradlew jacocoTestReport coveralls

after_failure:
  - "cat ./build/test-results/*.xml"
